spring:
  profiles:
    active: local # local 프로필과 test 프로필이 다르게 동작. local 프로필에만 InitData 추가 로직 동작.

  datasource:
    url: jdbc:h2:tcp://localhost/~/development/h2/springboot-order-tdd
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true # QueryDSL을 JPQL 주석으로 볼 수 있다.


logging:
  level:
    org.hibernate.sql: debug
